import { Metadata } from "next";
import { Raleway } from "next/font/google";
import Header from "../components/header";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"], display: 'swap' });

export const metadata: Metadata = {
  title: "NerdBox Notes",
  description: "Generated by NerdBox",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
